# **Numpy: Arrays and Matrices**

In [1]:
import numpy as np

## **Create arrays**

In [5]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = [11, 22, 44, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

[11, 22, 44, 33, 66, 55] <class 'list'> 6 2244645080128
[11 22 44 33 66 55] <class 'numpy.ndarray'> 6 2244592070032


In [6]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = [11, True, 22, 44, False, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

[11, True, 22, 44, False, 33, 66, 55] <class 'list'> 8 2244645172160
[11  1 22 44  0 33 66 55] <class 'numpy.ndarray'> 8 2244644834832


In [7]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = [11.5, True, 22, 44, False, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

[11.5, True, 22, 44, False, 33, 66, 55] <class 'list'> 8 2244644911936
[11.5  1.  22.  44.   0.  33.  66.  55. ] <class 'numpy.ndarray'> 8 2244592069552


In [8]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = ["11.5", True, 22, 44.5, False, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

['11.5', True, 22, 44.5, False, 33, 66, 55] <class 'list'> 8 2244645180480
['11.5' 'True' '22' '44.5' 'False' '33' '66' '55'] <class 'numpy.ndarray'> 8 2244644834928


In [10]:
list1 = range(1, 10, 2)
print(list1)
arr1 = np.array(list1)
print(arr1)

range(1, 10, 2)
[1 3 5 7 9]


In [31]:
# list2 = [range(1, 10), range(11, 20)] # list of lists
list2 = [[11, 22, 33, 44], [66, 77, 88, 99]]
print(list2)
arr2 = np.array(list2) # 2-D array
print(arr2)
for item in np.nditer(arr2):  # iterating over the ndarray in a row-major fashion
    print(item, end = ", ")

[[11, 22, 33, 44], [66, 77, 88, 99]]
[[11 22 33 44]
 [66 77 88 99]]
11, 22, 33, 44, 66, 77, 88, 99, 

In [29]:
print("Good", "Morning", sep="-", end=", ")
print("To all")

Good-Morning, To all


In [19]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [20]:
# function with variable number of arguments
def funct1(*arg):  # arg is defined forcefully as tuple type
    print(arg, len(arg), type(arg))
funct1("Amit", "Developer")
funct1("Amit", "Developer", "Pune")
funct1("Amit", "Developer", "Pune", "IBM")

('Amit', 'Developer') 2 <class 'tuple'>
('Amit', 'Developer', 'Pune') 3 <class 'tuple'>
('Amit', 'Developer', 'Pune', 'IBM') 4 <class 'tuple'>


In [23]:
# function with variable number of arguments
def funct2(**kwarg):  # kwarg is defined forcefully as dictionary type
    print(kwarg, len(kwarg), type(kwarg))
funct2(name="Amit", desig="Developer")
funct2(name="Amit", desig="Developer", location="Pune")
funct2(name="Amit", desig="Developer", location="Pune", company="IBM")

{'name': 'Amit', 'desig': 'Developer'} 2 <class 'dict'>
{'name': 'Amit', 'desig': 'Developer', 'location': 'Pune'} 3 <class 'dict'>
{'name': 'Amit', 'desig': 'Developer', 'location': 'Pune', 'company': 'IBM'} 4 <class 'dict'>


In [27]:
# function with variable number of arguments
def funct3(*arg, **kwarg):
    print(arg, len(arg), type(arg))
    print(kwarg, len(kwarg), type(kwarg), "\n")

funct3("Amit", "Developer", location="Pune", company="IBM", salary=80000)
funct3("Amit", "Developer")
funct3(location="Pune", company="IBM", salary=80000)

('Amit', 'Developer') 2 <class 'tuple'>
{'location': 'Pune', 'company': 'IBM', 'salary': 80000} 3 <class 'dict'> 

('Amit', 'Developer') 2 <class 'tuple'>
{} 0 <class 'dict'> 

() 0 <class 'tuple'>
{'location': 'Pune', 'company': 'IBM', 'salary': 80000} 3 <class 'dict'> 



In [35]:
# nd-array to list
list1 = [11, 33, 22, 55, 44, 66]
print(list1, len(list1), type(list1))
arr1 = np.array(list1)
print(arr1, len(arr1), type(arr1))
list2 = arr1.tolist()
print(list2, len(list2), type(list2))
list2 = list(arr1)  # not to be done
print(list2, len(list2), type(list2))

[11, 33, 22, 55, 44, 66] 6 <class 'list'>
[11 33 22 55 44 66] 6 <class 'numpy.ndarray'>
[11, 33, 22, 55, 44, 66] 6 <class 'list'>
[11, 33, 22, 55, 44, 66] 6 <class 'list'>


In [36]:
# nd-array to list
list1 = [[11, 33, 22, 55], [44, 66, 88, 77]] # list of lists
print(list1, len(list1), type(list1))
arr1 = np.array(list1)
print(arr1, len(arr1), type(arr1))
list2 = arr1.tolist()
print(list2, len(list2), type(list2))
list2 = list(arr1)  # not to be done
print(list2, len(list2), type(list2))

[[11, 33, 22, 55], [44, 66, 88, 77]] 2 <class 'list'>
[[11 33 22 55]
 [44 66 88 77]] 2 <class 'numpy.ndarray'>
[[11, 33, 22, 55], [44, 66, 88, 77]] 2 <class 'list'>
[array([11, 33, 22, 55]), array([44, 66, 88, 77])] 2 <class 'list'>


In [43]:
# examining arrays
arr1 = np.array([11, 33, 22, 44, 55, 66])
print(arr1, len(arr1), type(arr1))
print(arr1.dtype, arr1.size, arr1.ndim, arr1.shape)

[11 33 22 44 55 66] 6 <class 'numpy.ndarray'>
int32 6 1 (6,)


In [46]:
arr2 = np.array([[11, 33, 22, 44], [55, 66, 77, 88]])
print(arr2, len(arr2), type(arr2))
print(arr2.dtype, arr2.size, arr2.ndim, arr2.shape)

[[11 33 22 44]
 [55 66 77 88]] 2 <class 'numpy.ndarray'>
int32 8 2 (2, 4)


In [48]:
var1 = (10)
print(var1, type(var1))
var1 = (10,)  # singleton representation of a tuple
print(var1, type(var1))

10 <class 'int'>
(10,) <class 'tuple'>


In [56]:
arr1 = np.array([11, 33, 22, 44], dtype="int8")
print(arr1, len(arr1), type(arr1), arr1.dtype)
arr2 = np.array([[11, 33, 22, 44], [55, 66, 77, 88]], dtype="int8")
print(arr2, len(arr2), type(arr2), arr2.dtype)

[11 33 22 44] 4 <class 'numpy.ndarray'> int8
[[11 33 22 44]
 [55 66 77 88]] 2 <class 'numpy.ndarray'> int8


In [63]:
# create special arrays
print(np.zeros(10))
print(np.zeros(10, dtype="int8"), np.zeros(10).astype(int))
print(np.zeros(10) + 5) # vector & scalar operation -> vector
print(np.zeros((3, 6)))
print(np.zeros((3, 6)).astype(int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [75]:
# create special arrays
print(np.ones(10))
print(np.ones(10, dtype="int8"), np.ones(10).astype(int))
print(np.ones(10) * 5) # vector & scalar operation -> vector
print(np.ones((3, 6)))
print(np.ones((3, 6)).astype(int))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1] [1 1 1 1 1 1 1 1 1 1]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [70]:
print(np.linspace(0, 1, 5)) # 0 to 1 (all inclusive) 5 equi-distant numbers
print(np.linspace(0, 10, 11))
print(np.linspace(0, 10, 11).astype(int))

[0.   0.25 0.5  0.75 1.  ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [81]:
print(np.logspace(0, 3, 4))
print(np.logspace(0, 3, 4, base=10))
print(np.logspace(0, 3, 4, base=2))
print(np.logspace(0, 10))  # by default 50 numbers

[   1.   10.  100. 1000.]
[   1.   10.  100. 1000.]
[1. 2. 4. 8.]
[1.00000000e+00 1.59985872e+00 2.55954792e+00 4.09491506e+00
 6.55128557e+00 1.04811313e+01 1.67683294e+01 2.68269580e+01
 4.29193426e+01 6.86648845e+01 1.09854114e+02 1.75751062e+02
 2.81176870e+02 4.49843267e+02 7.19685673e+02 1.15139540e+03
 1.84206997e+03 2.94705170e+03 4.71486636e+03 7.54312006e+03
 1.20679264e+04 1.93069773e+04 3.08884360e+04 4.94171336e+04
 7.90604321e+04 1.26485522e+05 2.02358965e+05 3.23745754e+05
 5.17947468e+05 8.28642773e+05 1.32571137e+06 2.12095089e+06
 3.39322177e+06 5.42867544e+06 8.68511374e+06 1.38949549e+07
 2.22299648e+07 3.55648031e+07 5.68986603e+07 9.10298178e+07
 1.45634848e+08 2.32995181e+08 3.72759372e+08 5.96362332e+08
 9.54095476e+08 1.52641797e+09 2.44205309e+09 3.90693994e+09
 6.25055193e+09 1.00000000e+10]


In [88]:
list1 = range(10)
print(list1, type(list1), list(list1), type(list(list1)))
arr1 = np.arange(10)
print(arr1, len(arr1), type(arr1))
arr2 = np.arange(10).astype(float)
print(arr2, arr2.shape)
arr2 = np.arange(10, dtype="float")
print(arr2, arr2.shape)

range(0, 10) <class 'range'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>
[0 1 2 3 4 5 6 7 8 9] 10 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] (10,)
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] (10,)


## **reshaping**

In [99]:
matrix = np.arange(10, dtype=float)
print(matrix, matrix.shape)
matrix = np.arange(10, dtype=float).reshape(2, 5)
print(matrix, matrix.shape)
matrix = np.arange(10, dtype=float).reshape(-1, 5)
print(matrix, matrix.shape)
print()
matrix = np.arange(10).astype(float).reshape(2, -1)
print(matrix, matrix.shape)
matrix = np.arange(10).reshape(-1, 5).astype(float)
print(matrix, matrix.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] (10,)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] (2, 5)


In [103]:
matrix = np.arange(12).reshape(2, 2, -1).astype(float)
print(matrix)

[[[ 0.  1.  2.]
  [ 3.  4.  5.]]

 [[ 6.  7.  8.]
  [ 9. 10. 11.]]]


In [108]:
matrix =np.arange(10).reshape(2, 5)
print(matrix)
print(matrix.flatten())  # multi-dimestional array to one dimensional array conversion
print(matrix.T)  # transpose of a matrix
print(matrix.transpose())  # transpose of a matrix

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [110]:
matrix = np.arange(10, dtype = float).reshape(2, 5)
print(matrix)
print("Stored in the C-style order (Row major):")
cmatrix = matrix.copy(order = 'C')
print(cmatrix)
for item in np.nditer(cmatrix):
    print(item, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Stored in the C-style order (Row major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

In [112]:
matrix = np.arange(10, dtype = float).reshape(2, 5)
print(matrix)
print("Stored in the F-style order (Column major):")
cmatrix = matrix.copy(order = 'F')
print(cmatrix)
for item in np.nditer(cmatrix):
    print(item, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Stored in the F-style order (Column major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 

In [114]:
var1 = 10
print(var1, type(var1))
def funct1():
    print("Hello")
print(type(funct1))

10 <class 'int'>
<class 'function'>


In [119]:
var1 = 100; var2 = 200
print(var1 + var2)
print(var1.__add__(var2))
print(var1, type(var1), var2, type(var2))

300
300
100 <class 'int'> 200 <class 'int'>


## **append, insert, delete and sort operations**

In [120]:
matrix = np.arange(10)
print(matrix, len(matrix))
matrix = np.append(matrix, [11, 22, 33])
print(matrix, len(matrix))
matrix  = np.append(matrix, [111, 222])
print(matrix, len(matrix))

[0 1 2 3 4 5 6 7 8 9] 10
[ 0  1  2  3  4  5  6  7  8  9 11 22 33] 13
[  0   1   2   3   4   5   6   7   8   9  11  22  33 111 222] 15


In [147]:
matrix = np.arange(10)
print(matrix, len(matrix))
matrix = np.insert(matrix, 3, [111, 333, 222])
print(matrix)

[0 1 2 3 4 5 6 7 8 9] 10
[  0   1   2 111 333 222   3   4   5   6   7   8   9]


In [124]:
# index ->         0   1   2   3   4   5   6   7
matrix = np.array([11, 33, 66, 55, 88, 77, 99, 22])
print(matrix, len(matrix))
matrix = np.delete(matrix, [6, 1, 2])
print(matrix, len(matrix))

[11 33 66 55 88 77 99 22] 8
[11 55 88 77 22] 5


In [129]:
matrix = np.array([11, 33, 66, 55, 88, 77, 99, 22])
print(matrix)
matrix1 = np.sort(matrix)
print(matrix1)
matrix2 = np.sort(-matrix)
print(matrix2)
matrix3 = -np.sort(-matrix)
print(matrix3)
matrix4 = np.sort(matrix)[::-1]
print(matrix4)

[11 33 66 55 88 77 99 22]
[11 22 33 55 66 77 88 99]
[-99 -88 -77 -66 -55 -33 -22 -11]
[99 88 77 66 55 33 22 11]
[99 88 77 66 55 33 22 11]


In [138]:
arr1 = np.arange(12).reshape(3, 4)
print(arr1)
arr2 = np.arange(12, 24).reshape(3, 4)
print(arr2)
arr3 = np.concatenate((arr1, arr2))
print(arr3)
print("Joining two matrices along axis-0...")
arr3 = np.concatenate((arr1, arr2))
print(arr3)
print("Joining two matrices along axis-1...")
arr3 = np.concatenate((arr1, arr2), axis = 1)
print(arr3)
print(arr3.shape, arr3.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Joining two matrices along axis-0...
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Joining two matrices along axis-1...
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
(3, 8) 2


In [139]:
print("Stack two arrays along axis-0...")
arr4 = np.stack((arr1, arr2), axis = 0)
print(arr4)
print("Stack two arrays along axis-1...")
arr4 = np.stack((arr1, arr2), axis = 1)
print(arr4)
print(arr4.shape, arr4.ndim)

Stack two arrays along axis-0...
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Stack two arrays along axis-1...
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
(3, 2, 4) 3


## **slicing and indexing**

In [145]:
# L to R index   0   1   2   3   4   5   6   7
# R to L index  -8  -7  -6  -5  -4  -3  -2  -1
arr1 = np.array([22, 44, 33, 55, 77, 66, 88, 99])
print(arr1)
print(arr1[2], arr1[-6], arr1[7], arr1[-1])
print(arr1[:4], arr1[4:], arr1[::-1])

[22 44 33 55 77 66 88 99]
33 33 99 99
[22 44 33 55] [77 66 88 99] [99 88 66 77 55 33 44 22]


In [150]:
arr2 = np.arange(20).reshape(4, 5)
print(arr2)
print(arr2[1:3, 1:4])
arr2[[0, -1], :] = 0
arr2[:, [0, -1]] = 0
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 6  7  8]
 [11 12 13]]
[[ 0  0  0  0  0]
 [ 0  6  7  8  0]
 [ 0 11 12 13  0]
 [ 0  0  0  0  0]]
