# **Numpy: Arrays and Matrices**

In [1]:
import numpy as np

## **Create arrays**

In [5]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = [11, 22, 44, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

[11, 22, 44, 33, 66, 55] <class 'list'> 6 2244645080128
[11 22 44 33 66 55] <class 'numpy.ndarray'> 6 2244592070032


In [6]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = [11, True, 22, 44, False, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

[11, True, 22, 44, False, 33, 66, 55] <class 'list'> 8 2244645172160
[11  1 22 44  0 33 66 55] <class 'numpy.ndarray'> 8 2244644834832


In [7]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = [11.5, True, 22, 44, False, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

[11.5, True, 22, 44, False, 33, 66, 55] <class 'list'> 8 2244644911936
[11.5  1.  22.  44.   0.  33.  66.  55. ] <class 'numpy.ndarray'> 8 2244592069552


In [8]:
# create arrays from lists
# remember arrays will have data of same data types
data1 = ["11.5", True, 22, 44.5, False, 33, 66, 55]
print(data1, type(data1), len(data1), id(data1))
arr1 = np.array(data1)
print(arr1, type(arr1), len(arr1), id(arr1))

['11.5', True, 22, 44.5, False, 33, 66, 55] <class 'list'> 8 2244645180480
['11.5' 'True' '22' '44.5' 'False' '33' '66' '55'] <class 'numpy.ndarray'> 8 2244644834928


In [10]:
list1 = range(1, 10, 2)
print(list1)
arr1 = np.array(list1)
print(arr1)

range(1, 10, 2)
[1 3 5 7 9]


In [31]:
# list2 = [range(1, 10), range(11, 20)] # list of lists
list2 = [[11, 22, 33, 44], [66, 77, 88, 99]]
print(list2)
arr2 = np.array(list2) # 2-D array
print(arr2)
for item in np.nditer(arr2):  # iterating over the ndarray in a row-major fashion
    print(item, end = ", ")

[[11, 22, 33, 44], [66, 77, 88, 99]]
[[11 22 33 44]
 [66 77 88 99]]
11, 22, 33, 44, 66, 77, 88, 99, 

In [29]:
print("Good", "Morning", sep="-", end=", ")
print("To all")

Good-Morning, To all


In [19]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.



In [20]:
# function with variable number of arguments
def funct1(*arg):  # arg is defined forcefully as tuple type
    print(arg, len(arg), type(arg))
funct1("Amit", "Developer")
funct1("Amit", "Developer", "Pune")
funct1("Amit", "Developer", "Pune", "IBM")

('Amit', 'Developer') 2 <class 'tuple'>
('Amit', 'Developer', 'Pune') 3 <class 'tuple'>
('Amit', 'Developer', 'Pune', 'IBM') 4 <class 'tuple'>


In [23]:
# function with variable number of arguments
def funct2(**kwarg):  # kwarg is defined forcefully as dictionary type
    print(kwarg, len(kwarg), type(kwarg))
funct2(name="Amit", desig="Developer")
funct2(name="Amit", desig="Developer", location="Pune")
funct2(name="Amit", desig="Developer", location="Pune", company="IBM")

{'name': 'Amit', 'desig': 'Developer'} 2 <class 'dict'>
{'name': 'Amit', 'desig': 'Developer', 'location': 'Pune'} 3 <class 'dict'>
{'name': 'Amit', 'desig': 'Developer', 'location': 'Pune', 'company': 'IBM'} 4 <class 'dict'>


In [27]:
# function with variable number of arguments
def funct3(*arg, **kwarg):
    print(arg, len(arg), type(arg))
    print(kwarg, len(kwarg), type(kwarg), "\n")

funct3("Amit", "Developer", location="Pune", company="IBM", salary=80000)
funct3("Amit", "Developer")
funct3(location="Pune", company="IBM", salary=80000)

('Amit', 'Developer') 2 <class 'tuple'>
{'location': 'Pune', 'company': 'IBM', 'salary': 80000} 3 <class 'dict'> 

('Amit', 'Developer') 2 <class 'tuple'>
{} 0 <class 'dict'> 

() 0 <class 'tuple'>
{'location': 'Pune', 'company': 'IBM', 'salary': 80000} 3 <class 'dict'> 

